### ISSUE TITLE
[BUG] Space race mission does not sync during multiplayer game

### ISSUE THREAD

**Issue by WizzardMaker** [WizzardMaker/AirlineTycoon#1]
**Describe the bug**
You have to build a rocket, stage by stage in this mission. The mission was never meant for the multiplayer, making it not sync its progress

**Expected behavior**
The stages of every player should be synced

**Info**
Related code in `Dialog.cpp:5247`
Fix would be to create a new event and send it each time someone buys a part

**Comment by mr-dev-cmd** [comment]
Hi.
In Version 1.6.2 it seems to work. Dont know if you already know.
