### ISSUE TITLE
[BUG] Tutorial crash game in first mission

### ISSUE THREAD

**Issue by mr-dev-cmd** [WizzardMaker/AirlineTycoon#19]
**Your current version**
v1.6 - Linux (ubuntu 22.04)

**Describe the bug**
When start the first mission in the first campaign the tutorial crashes game when clicking on the globe.

**To Reproduce**
1. Go to office after morning meeting  as part of tutorial
2. Click on globe as part of tutorial

**Expected behavior**
no crash

**Crash dumps**
no crash report, no message

**Comment by mr-dev-cmd** [comment]
when you abort the tutorial, the globe can be clicked and everything works normal.

**Comment by Torston420** [comment]
Reproducing prints the following to Terminal:
`INFO: Herc || Block.cpp: Default case should not be reached.`

`Misc.cpp:2078: void DebugBreak(): Assertion '0' failed`

The crash can be avoided by loading the Globe & Filofax before starting the Tutorial, successfully doing so does not produce the `Default case should not be reached.` error when attempting to perform the Tutorial objective.

**Comment by WizzardMaker** [comment]
Crash was caused by erroneously added default exceptions - should now be fixed
