### ISSUE TITLE
[BUG] [1.6] Tutorial cannot be completed due to Filofax labels not accepting input

### ISSUE THREAD

**Issue by Torston420** [WizzardMaker/AirlineTycoon#20]
**Your current version**
1.6 Pre-Release (Artix Linux)

**Describe the bug**
Following the Tutorial after having already loaded the Globe & Filofax prior causes the Orders/Cargo/Routes labels to become unresponsive while the Tutorial is still active, causing it to be uncompletable.

**To Reproduce**
1. Load the Globe & Filofax via any means
2. Open the Pause Menu and Quit Session
3. Start the mission A New Job and allow the Tutorial to take place
4. Follow the Tutorial

**Expected behavior**
The Orders/Cargo/Routes Labels loading the tabs correctly and the Tutorial being completable.

**Screenshots**
![Example of glitch](https://user-images.githubusercontent.com/30721808/202591577-fa2c4f7d-47b7-4205-8c37-c0f1565733ea.png)

**Crash dumps**
N/A, Does not crash.

**Additional context**
This issue is no longer present in any form if the Tutorial is skipped.

**Comment by WizzardMaker** [comment]
Related to #19 - the data refresh wasn't correctly handling "no data"-ish states, that are used by the tutorial. Reloading the mission after previously using the filofax seems to be a bug in of itself, because the filofax isn't set to the "no data" state after starting the tutorial

should be fixed now

**Comment by Torston420** [comment]
The crash was fixed, the frozen Filofax was not.
![Example of glitch](https://user-images.githubusercontent.com/30721808/202591577-fa2c4f7d-47b7-4205-8c37-c0f1565733ea.png)

**Comment by WizzardMaker** [comment]
Oh yeah, right

Forgot to add the state reset on mission launch
Will be added as soon as I can - sorry about that
