### ISSUE TITLE
[BUG] Parts of space rocket cost only 200k

### ISSUE THREAD

**Issue by mr-dev-cmd** [WizzardMaker/AirlineTycoon#24]
**Your current version**
1.6.1

**Describe the bug**
In the last mission of the first campaign. "Die letzte Grenze". the parts of the rocket have correct price, but when you buy them, only 200.000$ are taken from bank account. So in total you only need 2 Mio for the complete mission.

**To Reproduce**
1. Start mission "Die letzte Grenze"
2. Go to Nasa
3. Buy all the first 3 parts. Only 600.000 real costs.
4. with the other parts it is the same, but you are only able to buy when your bank account would have enough money

**Expected behavior**
costs like price

**Comment by WizzardMaker** [comment]
was a bug in the price calculation, should be fixed now
