### ISSUE TITLE
[BUG] Game Crasht always at the same time in the savegame

### ISSUE THREAD

**Issue by Be-Mann** [WizzardMaker/AirlineTycoon#37]
**Your current version**
What game version are you on?
ATD Version 1.7.0 Pre-Release

**Describe the bug**
Game Crasht always at the same time in the savegame, no matter what I do, unfortunately, I think in the crash is not really something helpful in it, but have this times attached.

**To Reproduce**
Since the game always crashes at the same time in the savegame no matter what I do, it is reproducible. 

**Expected behavior**
I expected to continue playing and not end up on the desktop

**Screenshots**
No screenshots available

**Crash dumps**
[crash-537951.txt](https://github.com/WizzardMaker/AirlineTycoon/files/11809353/crash-537951.txt)
[Game-Crash-Event Viewer.txt](https://github.com/WizzardMaker/AirlineTycoon/files/11809381/Game-Crash-Event.Viewer.txt)
[Report.wer.txt](https://github.com/WizzardMaker/AirlineTycoon/files/11809384/Report.wer.txt)
[CrashDump_At.exe.42124.zip](https://github.com/WizzardMaker/AirlineTycoon/files/11810718/CrashDump_At.exe.42124.zip)

**Additional context**
I have added the savegame, city and routes files, maybe this can help to solve the problem.
[AT Crash Data.zip](https://github.com/WizzardMaker/AirlineTycoon/files/11809391/AT.Crash.Data.zip)

**Comment by WizzardMaker** [comment]
What original version of AT do you have? (From GoG, Steam, CD and also AT Deluxe, First Class or Original?)

The error seems to come from one of the airport animation files

> [for me]
> attached sentry error ids: 3c61a5010c0f43bca61ad92cadd28029

**Comment by Be-Mann** [comment]
> What original version of AT do you have?

I use the GoG version (Airline Tycoon Deluxe VERSION 1.03)

> The error seems to come from one of the airport animation files

Can this come from the added airport "Düsseldorf"? Not that I have built in a mistake

These are the only changes, so I took the precaution of including the City and Routes, just so we can eliminate this as a source of error

**Comment by Be-Mann** [comment]
Is there any news about this?

**Comment by WizzardMaker** [comment]
It was an amalgamation of various issues, that lead to your crash.

Should be fixed in the next version (You can grab the artifact from https://github.com/WizzardMaker/AirlineTycoon/actions/runs/5636295885 if you want to test the fix)

**Comment by Be-Mann** [comment]
Thank you very much, great work, I have tested briefly times on and it seems to be fixed, but will test it later times in detail to give feedback if still a problem occurs, otherwise see the problem as fixed.

**Comment by WizzardMaker** [comment]
Great!
Feel free to reopen this issue if a related crash occurs

**Comment by Be-Mann** [comment]
Hi habe mal weiter gespielt und bin auf einen neuen Absturz gestoßen, der sehr ähnlich aussieht von der crash log, daher habe ich mich entschlossen diesen Post wieder zu öffnen.
Ich habe dies sowohl mit der damaligen als auch mit der aktuellen Pre-Release Version [fix/various](https://github.com/WizzardMaker/AirlineTycoon/actions/runs/7514040166) getestet.

Der Absturz tritt auf wenn der Laptop geöffnet wird und der Akku leer ist.

Ach und die aktuelle Pre-Release Version ist ausschließlich in Englisch, liegt wohl daran dass in der `src/Takeoff.cpp` dies umgestellt wurde und die Argumente noch ausgeklammert sind

```diff
- gLanguage = LANGUAGE_D;
+ gLanguage = LANGUAGE_E;
```

----------

Hi I've been playing around and came across a new crash that looks very similar from the crash log, so I decided to reopen this post.
I have tested this with both the previous and the current pre-release version [fix/various](https://github.com/WizzardMaker/AirlineTycoon/actions/runs/7514040166).

The crash occurs when the laptop is opened and the battery is empty.

Oh and the current pre-release version is only in English, probably because in the `src/Takeoff.cpp` this has been changed and the arguments are still excluded

```diff
- gLanguage = LANGUAGE_D;
+ gLanguage = LANGUAGE_E;
```

![image](https://github.com/WizzardMaker/AirlineTycoon/assets/25839760/0962ad5e-614b-4bb8-849a-ef7c22a180e2)
[crash-121754.txt](https://github.com/WizzardMaker/AirlineTycoon/files/14059623/crash-121754.txt)
[crash-669596.txt](https://github.com/WizzardMaker/AirlineTycoon/files/14059624/crash-669596.txt)
[5f49b968-b663-46c2-83a7-21f33890e45f.dmp](https://github.com/WizzardMaker/AirlineTycoon/files/14059626/5f49b968-b663-46c2-83a7-21f33890e45f.dmp)
[ba9b18c0-5d48-44d5-992b-d7fd83b44429.dmp](https://github.com/WizzardMaker/AirlineTycoon/files/14059629/ba9b18c0-5d48-44d5-992b-d7fd83b44429.dmp)
[b51e2d62-56bd-4c2c-86c7-1f9ad65209b0.dmp](https://github.com/WizzardMaker/AirlineTycoon/files/14059628/b51e2d62-56bd-4c2c-86c7-1f9ad65209b0.dmp)

**Comment by Be-Mann** [comment]
plz reopen @WizzardMaker
