### ISSUE TITLE
[BUG] Game Crash after watching Intro

### ISSUE THREAD

**Issue by mr-dev-cmd** [WizzardMaker/AirlineTycoon#39]
**Your current version**
1.7 Linux

**Describe the bug**
After watching (or only start and abort) the Intro Video the main menu appears without the typical sound. The next click on one of the menu buttons crash the game.

**To Reproduce**
1. Start game
2. Click on 'Intro'
3. Abort the Intro by click mouse button
4. Hear already no sound
5. Klick on any menu crashs game

**Expected behavior**
normal menu after Intro and no crash

**Additional context**
The problem started with the last update. The version without the new AT.json config file (v1.6.2?) was still working. 

This is the terminal output:
INFO: SBNetwork || Started SBNetwork
INFO: Herc || Airline Tycoon Deluxe logfile
INFO: Herc || VERSION 1.7.0 RELEASE
INFO: Herc || ===============================================================================
INFO: Herc || Copyright (C) 2002 Spellbound Software
INFO: Herc || TakeOff.Cpp was compiled at Jun 19 2023 at 10:48:53
INFO: Herc || ===============================================================================
INFO: Herc || logging starts Wed Jun 28 20:19:04 2023
INFO: Herc || Using hardware accelerated presentation
INFO: Herc || ====================================================================
INFO: Herc || Exception in File /home/***/Airline_Source/AirlineTycoon/src/SBLib/source/GfxLib.cpp, Line 69:
INFO: Herc || Can't open /home/***/AirlineTycoonDeluxe/room/titel2.gli!
INFO: Herc || ====================================================================
INFO: Herc || C++ Exception thrown. Program will probably be terminated.
INFO: Herc || Exception was correctly handled
INFO: Sound || Error during audio load of file "/home/***/AirlineTycoonDeluxe/sound/klack0.raw": Invalid source format
INFO: Sound || Error during audio load of file "/home/***/AirlineTycoonDeluxe/sound/klack1.raw": Invalid source format
INFO: Sound || Error during audio load of file "/home/***/AirlineTycoonDeluxe/sound/klack2.raw": Invalid source format
INFO: Sound || Error during audio load of file "/home/***/AirlineTycoonDeluxe/sound/change.raw": Invalid source format
Segmentation fault (core dumped)

**Comment by WizzardMaker** [comment]
Did you remove the previous settings file in the ATD folder? 
You have to delete that
A previous implementation filled the file with incorrect values

**Comment by mr-dev-cmd** [comment]
You were right.
I deleted the AT.json and the issue is solved.

when I recreated my settings, I found that:
"OptionEnableDigi": false
caused the problem. Its in the new settings file on true and I have no idea how to change that in game anyway. So it should cause no issues anymore, as long as not changed manually in the AT.json to false.
