### ISSUE TITLE
[BUG] Clipboard 'page right' button in HR  has wrong position

### ISSUE THREAD

**Issue by WizzardMaker** [WizzardMaker/AirlineTycoon#4]
**Your current version**
ATD (SDL) Version 1.3 Pre-Release

**Describe the bug**
The button should be a bit to the right from where it currently is

**Screenshots**
![image](https://user-images.githubusercontent.com/7768485/113778436-a48d2200-972c-11eb-95a4-6bb13276b039.png)

**Comment by mertenpopp** [comment]
Did not notice this one. Maybe related to a specific SDL version.
