### ISSUE TITLE
[BUG] Useless files and folders created in Linux

### ISSUE THREAD

**Issue by mr-dev-cmd** [WizzardMaker/AirlineTycoon#40]
**Your current version**
v1.7 Linux

**Describe the bug**
1. The game still creates the old settings folder "~/.local/share/Spellbound/" but without any content.

2. When the game executable is started via terminal from another location (path), the game creates a unnecessary AT.json in the current path of the terminal.

**To Reproduce**
For the first bug, just start the game in Linux
For the second bug:
1. Open Terminal
2. The terminal path is usually the home folder ~/
3. enter the path to the AT executable, e.g. '/home/USER/Games/AirlineTycoonDeluxe/AT'
4. the game starts and uses the AT.json file near in the AirlineTycoonDeluxe folder what is normal
5. the game also creates an unnecessary AT.json in the ~/ folder what is the current path of the terminal

**Expected behavior**
don't create useless folders and files

**Comment by WizzardMaker** [comment]
The absolute path to the executable folder is now used, instead of just the relative path "AT.json"

**Comment by mr-dev-cmd** [comment]
It's working now.
Good job.
