### ISSUE TITLE
[BUG] Star base prices incorrect

### ISSUE THREAD

**Issue by WizzardMaker** [WizzardMaker/AirlineTycoon#44]
**Your current version**
v1.7.0

**Describe the bug**
So, the last map of the second campaign, we kinda are doing the same thing as in the final map of the first one - except instead of making a rocket, we're buying parts for the space station. Mechanically its exactly the same thing, visually it just gives you a special telescope, different graphics for the objective, and the Nasa shop seems to work exactly the same.
However, as I was buying up the parts of the Space Station after accumulating all the cash, I've noticed it... took the wrong amounts of money from my account. I thought it might be the "security manager"'s discount, but that wasn't it.
Looking at the log in the checkbook, the situation explains itself pretty easily - the scenario is looking up prices from that final map of the first campaign - the one with the rocket. Technically it doesn't change that much, really. The prices are just wildly mismatched, though in total the cost of all components comes out very similarly anyways.
So, seems something wrong is plugged in in the map, and it just grabs the rocket parts prices instead of the star-base prices.
For info - I haven't encountered any gamebreaking stuff, the scenario still ended in a victory, same so far with any other map. 

**To Reproduce**
-- todo --

**Expected behavior**

**Screenshots**
![image](https://github.com/WizzardMaker/AirlineTycoon/assets/7768485/ae4cf582-6c60-4e74-9774-5b88d0958327)

![image](https://github.com/WizzardMaker/AirlineTycoon/assets/7768485/d0976a7c-2977-4356-8641-50a5ae8cd89f)

**Additional context**
Reported on discord by @kefe

**Comment by wackfx** [comment]
Patched in #52
