### ISSUE TITLE
[BUG] [Linux] Always falls back to software presentation

### ISSUE THREAD

**Issue by Torston420** [WizzardMaker/AirlineTycoon#46]
**Your current version**
1.7 fix/various, version doesn't seem to matter though
Artix Linux, SDL 2.28.3

**Describe the bug**
Game always falls back to software presentation, I do not know of a way to force hardware presentation.

**Additional context**
Output of 'pacman -Qs sdl2'

```
local/lib32-sdl2 2.28.3-1
    A library for portable low-level access to a video framebuffer, audio output, mouse, and keyboard
local/lib32-sdl2_image 2.6.3-1
    A simple library to load images of various formats as SDL surfaces
local/lib32-sdl2_mixer 2.6.3-1
    A simple multi-channel audio mixer
local/lib32-sdl2_ttf 2.20.2-1
    Library that allows you to use TrueType fonts in your SDL applications (Version 2) (32-bit)
local/python-pysdl2 0.9.16-1
    Python ctypes wrapper around SDL2
local/sdl2 2.28.3-1
    A library for portable low-level access to a video framebuffer, audio output, mouse, and keyboard (Version 2)
local/sdl2_image 2.6.3-1
    A simple library to load images of various formats as SDL surfaces (Version 2)
local/sdl2_mixer 2.6.3-2
    A simple multi-channel audio mixer (Version 2)
local/sdl2_net 1:2.2.0-1
    A small sample cross-platform networking library (Version 2)
local/sdl2_ttf 2.20.2-1
    A library that allows you to use TrueType fonts in your SDL applications (Version 2)
```

**Comment by WizzardMaker** [comment]
Can you check https://github.com/WizzardMaker/AirlineTycoon/pull/38 for a possible fix?

I don't have a proper Linux machine to test - which makes it a bit hard to pinpoint the exact cause for this problem.

There were a few incorrect remaining calls to non-renderer functions which could have lead to undefined behaviour manifesting in a fallback to software rendering

**Comment by Torston420** [comment]
`Using hardware accelerated presentation`! It works!

**Comment by WizzardMaker** [comment]
Great to hear - closing this issue as it now seems to work
