### ISSUE TITLE
[BUG] Create multiplayer game from save

### ISSUE THREAD

**Issue by perszing87** [WizzardMaker/AirlineTycoon#48]
**Your current version**
1.7.0

**Describe the bug**
When trying to host game from previously saved one there is no possibility to join using Direct IP - Join. When typing proper IP address of hosting PC nothing happens - only window with IP address form is closing.

**To Reproduce**
1. Host new game with Direct IP - Host
2. Join it with second PC with Direct IP - Join
3. Save game
4. Close current game
5. Host game with Direct IP - Host using previously saved file
6. Try to join it with second PC with Direct IP - Join

**Expected behavior**
Second PC should join game created from save file.

**Additional context**
Apparently it is working with RAKNet join. When I create game from save file using Direct IP - host I can find this session on second PC with RAKNet - Join and I am able to connect to it.

**Comment by WizzardMaker** [comment]
Should be fixed in 1.7.2
