### ISSUE TITLE
[BUG] game crashes when I try basically do almost anything.

### ISSUE THREAD

**Issue by Guybrush117** [WizzardMaker/AirlineTycoon#50]
**Your current version**
1.7.0
**Describe the bug**
I maybe fu**** up somthing by installing the patch. I play with the french version of the game and when I try to save/load a game, when i try to buy/sell stock athe bank, the game crashes.

**To Reproduce**
explained above, please note that I play with the french version of the game

try to save or load a game
go to the bank and try to buy/sell stock

**Expected behavior**
the game crashes

**Screenshots**

**Crash dumps**
If the game crashed, please check for crash dumps (%localappdata%\CrashDumps) and post them here.
[CrashDumps.zip](https://github.com/WizzardMaker/AirlineTycoon/files/12810745/CrashDumps.zip)

**Additional context**

**Comment by Guybrush117** [comment]
Hello ! 
First a big thank you adding the windowed mode in this game, but sadly I cannot play it because the game crashes a lot. Did I screw up the installation of your patch/fix, by any chance ?
Thank you and have a great day !

**Comment by WizzardMaker** [comment]
Hi there, thanks for sending the crash dumps, those really helped!

The crash comes from missing translation for a few text modifications we did on some dialog options. The game apparently doesn't like it when a text with a missing language gets loaded.

For now to fix your issue I can recommend to set your text language to English (or German, whatever you're more comfortable with) until I get to fix the crash.

My plan is it, to add a fallback to English for texts that are missing in a specific language, but if you want to, you could also add a french translation to all texts that we added: https://github.com/WizzardMaker/AirlineTycoon/blob/38a43f9569f9526e501e295c88acb0102804f0da/src/Takeoff.cpp#L2227-L2379

You don't need to edit the code or anything like that - just the texts are fine as well, I could add them to the code myself

**Comment by mr-dev-cmd** [comment]
Hi. After that change, I had the frensh texts everywhere. Maybe it is because of my retail CD version that not use a "de" folder.
I had tho change the line "const SLONG wantedLanguageIndex = 2;//gLanguage;"
to "const SLONG wantedLanguageIndex = 0;//gLanguage;" to get it german again.

Additionally I noticed that some of those new texts are not correct anymore. I could figure out that only the text lines containing "\r\n" are wrong.

**Comment by WizzardMaker** [comment]
Should be fixed in 1.7.2
