### ISSUE TITLE
[BUG] Game Crashes always at the same time in the savegame

### ISSUE THREAD

**Issue by ian5142** [WizzardMaker/AirlineTycoon#53]
**Your current version**
What game version are you on?
ATD Version 1.7.0 Pre-Release       NO MODS
Deluxe version from GOG, English text. 

**Describe the bug**
Game Crashes always at the same time in the savegame, no matter what I do.

**To Reproduce**
1. Load Savegame, wait under 30 sec.

**Expected behavior**
Not crashing.

**Screenshots**
N/A

**Crash dumps**
If the game crashed, please check for crash dumps (%localappdata%\CrashDumps) and post them here.
[AT.exe.37828.dmp](https://github.com/WizzardMaker/AirlineTycoon/files/14078560/AT.exe.37828.dmp)
[crash-901296.txt](https://github.com/WizzardMaker/AirlineTycoon/files/14078565/crash-901296.txt)
[debug.log](https://github.com/WizzardMaker/AirlineTycoon/files/14078566/debug.log)

**Comment by ian5142** [comment]
[game1.zip](https://github.com/WizzardMaker/AirlineTycoon/files/14078739/game1.zip)
Forgot the save game file.

**Comment by WizzardMaker** [comment]
Savegame does not crash in version 1.7.1 https://github.com/WizzardMaker/AirlineTycoon/releases/tag/v1.7.1-preview
