### ISSUE TITLE
[BUG] Version higher 1.7.0 dont start in windows

### ISSUE THREAD

**Issue by mr-dev-cmd** [WizzardMaker/AirlineTycoon#64]
**Your current version**
Last Version that starts is 1.7.0. Everything higher dont start. (Windows)

**Describe the bug**
The game dont start without any Information.
An empty debug file is written but not even an AT.json (if deleted before)

**To Reproduce**
1. Install a version higher than 1.7.0 in windows
2. Start the game

**Expected behavior**
Game should start

**Comment by WizzardMaker** [comment]
Hm.. weird, windows is the most stable version of the game

Not even writing the debug header leads me to thinking, that a dependency is probably either broken, out of date, or not correctly loading.

Do you have the sentry.dll and all other dlls from the zip extracted after your update to 1.7.1+?

Did it ask you to send a report to sentry? If not that means it crashed even before entering the main function (but after the globals init, as the debug class could create the debug.txt)

**Comment by mr-dev-cmd** [comment]
Hi, yes. I downloaded the zip file and extract everything into the game directory. The sentry folder and some files are written too. In the sessions.json is written this:
{"init":true,"sid":"09cdd6e0-b2ba-4d57-57c9-f94832c4173d","status":"ok","errors":0,"started":"2024-11-14T22:22:50.415Z","duration":0,"attrs":{"release":"VERSION 1.7.1 RELEASE","environment":"production"}}

The Linux version works. I just tried on my windows System and was surprised that it doesnt start.

**Comment by WizzardMaker** [comment]
What windows version and in what environment (VM, bare metal, etc.) are you running?

**Comment by mr-dev-cmd** [comment]
It's normal Windows Installation on it's own hard disk. It's Windows 10.
On my Niece computer with only a Windows 11 running is the same problem. Last running version is the 1.7.0.
Maybe some files missing in the zip file? Or I must install some depencies myself?

**Comment by WizzardMaker** [comment]
This could either be a debug vs. release library dependency thing, or maybe related to something else

So that I can test it on my end, what game version are you using? GoG, Steam, or retail?

**Comment by mr-dev-cmd** [comment]
The retail version

**Comment by WizzardMaker** [comment]
Okay, I can rule out that the release uses debug libraries.
I can't reproduce it on my dev machines - I'll try to find a new windows machine to further test it

Can you check/make sure that you have the latest Visual C++ redist. installed?

**Comment by mr-dev-cmd** [comment]
Thanks!
The Update of visual c++ redist solved my problems. Funny that my Niece have the same old Version running. Again: thanks.

**Comment by WizzardMaker** [comment]
Well, give it to Microsoft for not including something so essential into their OS

Happy to hear it works
