### ISSUE TITLE
[BUG] Missing 'myplanes' folder results in a crash

### ISSUE THREAD

**Issue by WizzardMaker** [WizzardMaker/AirlineTycoon#7]
**Your current version**
v1.3P

**Describe the bug**
If you talk to the plane designer the game crashes

**Expected behavior**
Not a crash

**Additional context**
Problem is caused by a bugged C++ version of std::filesystem

**Comment by WizzardMaker** [comment]
Fixed in the next released

**Comment by CaitMila** [comment]
Hi! Was v1.3 ever releaesd? I'm having this same issue where I can't create custom planes.

**Comment by WizzardMaker** [comment]
Yes, but it's a pre release

https://github.com/WizzardMaker/AirlineTycoon/releases/tag/v1.3P

**Comment by CaitMila** [comment]
Hmm, issue is persisting for me for some reason
