### ISSUE TITLE
[BUG] Planes can't carry more than 340 passenger

### ISSUE THREAD

**Issue by WizzardMaker** [WizzardMaker/AirlineTycoon#9]
**Your current version**
1.2H3

**Describe the bug**
A 345 passenger plane could not execute a 340 passenger order, even though the range was in check.

**To Reproduce**
-

**Additional context**
Possible plane: C5A Galaxy 345 passengers

**Comment by mertenpopp** [comment]
Could be related to first class / regular class division. Maybe try to reduce the number of first class seats.

**Comment by WizzardMaker** [comment]
Fixed in a2cb4aee74fd392bd13851da69a3c4f0b5dbb308
